apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wildfly-operator
  namespace: wildfly-operator
spec:
  interval: 2m
  releaseName: wildfly-operator
  chart:
    spec:
      chart: wildfly
#      version: "2.4.0"
      sourceRef:
        kind: HelmRepository
        name: wildfly
        namespace: flux-system
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
#    image:
#      repository: quay.io/wildfly/wildfly-operator
#      tag: "2.4.0"

#    watchNamespaces:
#      - wildfly-apps
